version: "3"
services:
  h5ai:
    container_name: h5ai
    build: .
    ports:
      - 8080:80
    volumes:
      - /tmp/h5ai:/var/www
      - ./options.json:/usr/share/h5ai/_h5ai/private/conf/options.json
    restart: always
    network_mode: "bridge"
